# Generated by Django 2.0.4 on 2018-04-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180421_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comment_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='category',
        ),
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='manager.Category'),
        ),
    ]
