# Generated by Django 2.0.4 on 2018-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180422_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ManyToManyField(blank=True, to='manager.Category'),
        ),
    ]
