# Generated by Django 2.0.4 on 2018-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreExtend', '0003_auto_20180421_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('P', 'Pirate'), ('N', 'Ninja'), ('R', 'Robot'), ('O', 'Other'), ('B', 'Non-binary')], max_length=1),
        ),
    ]
